name: build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'
      - run: |
          pipx install poetry || true
          poetry install
          poetry run python main.py
      - uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: new-build
          commit-message: Update dashboards
          title: Update dashboards
          delete-branch: true
          signoff: true
