name: tag

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'dasbboards/**'

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - run: |
          git config --global user.name 'BeryJu.io bot'
          git config --global user.email 'bot@beryju.org'
          version=$(python -m get_version)
          git tag $version
          git push --tags
